name: CI
# Rename with 'version' input for manually triggered builds
run-name: ${{ github.event.inputs.version }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Release version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          cache: 'pip'
      - run: pip install -r etc/requirements.txt

      - name: Enforce code formatting
        run: make fmt-check

      - name: Run tests
        run: make test

      - name: Ensure promoting does not alter current files
        run: make test-promote-no-diff

  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17 & release credentials
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.RELEASE_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Maven Central Release
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.version }}
          mvn --batch-mode -DskipTests deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.RELEASE_GPG_PASSPHRASE }}

      - name: Changelog
        run: make release_changelog.md

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.inputs.version }}
          tag_name: ${{ github.event.inputs.version }}
          target_commitish: main
          body_path: release_changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            src/main/kotlin/nyub/expekt/ExpectTests.kt
            src/main/kotlin/nyub/expekt/junit/ExpectTestExtension.kt
